Repository neo4j/docs-drivers, pull requests merged in 2020-12, with the labels that each got.

#172 publish Go Driver 4.2
  commonManual/asciidoc/get-started.adoc
  goManual/antora/antora.yml
  goManual/asciidoc/client-applications.adoc
Labels: 4.2, Dependancy on other PR, GO, THIS VERSION ONLY

#175 Remove dep instructions
  commonManual/asciidoc/session-api.adoc
  goManual/asciidoc/get-started.adoc
  goManual/asciidoc/session-api.adoc
  goManual/docbook/content-map.xml
Labels: 4.2, GO, bug

#176 update nav and heading levels
  commonManual/asciidoc/get-started.adoc
  goManual/antora/content-nav.adoc
  goManual/asciidoc/get-started.adoc
  goManual/asciidoc/session-api.adoc
Labels: 4.2, THIS VERSION ONLY

#177 update 4.2.0a2 to 4.2.1
  pythonManual/antora/antora.yml
Labels: 4.2, PYTHON, THIS VERSION ONLY
