Repository neo4j/docs-drivers, pull requests merged in 2021-03, with the labels that each got.

#185 Update javaScript version to 4.2.3
  jsManual/antora/antora.yml
Labels: 4.2, THIS VERSION ONLY

#186 Update javascript version to 1.7.8
  antora/antora.yml
Labels: 1.7, JAVASCRIPT, THIS VERSION ONLY

#187 Update Java driver to 4.2.2
  javaManual/antora/antora.yml
Labels: 4.2, JAVA, THIS VERSION ONLY

#188 update java driver version
  javaManual/antora/antora.yml
Labels: 4.2, JAVA, THIS VERSION ONLY

#189 updated neo4j version exact to 4.2.3
  dotnetManual/antora/antora.yml
  goManual/antora/antora.yml
  javaManual/antora/antora.yml
  jsManual/antora/antora.yml
  pythonManual/antora/antora.yml
Labels: 4.2, THIS VERSION ONLY

#190 update java driver and examples to 4.2.4
  javaManual/antora/antora.yml
Labels: 4.2, THIS VERSION ONLY
