Repository neo4j/docs-drivers, pull requests merged in 2021-01, with the labels that each got.

#180 Add antora files
  antora/antora.yml
  antora/content-nav.adoc
  asciidoc/index.adoc
Labels: 1.7, THIS VERSION ONLY

#179 Add antora files
  antora/antora.yml
  antora/content-nav.adoc
  asciidoc/index.adoc
Labels: 4.0, THIS VERSION ONLY

#178 Add antora files
  antora/antora.yml
  antora/content-nav.adoc
  asciidoc/index.adoc
Labels: 4.1, THIS VERSION ONLY

#174 Remove mention of being able to configure custom retry logic
  commonManual/asciidoc/session-api.adoc
Labels: 4.2

#181 Remove mention of being able to configure custom retry logic
  asciidoc/session-api.adoc
Labels: 4.1, cherry-pick

#182 Remove mention of being able to configure custom retry logic
  asciidoc/session-api.adoc
Labels: 4.0, cherry-pick
