Repository neo4j/docs-drivers, pull requests merged in 2021-10, with the labels that each got.

#225 Adding a section and example on how to use multiple transactions with…
  commonManual/asciidoc/session-api.adoc
  dotnetManual/asciidoc/session-api.adoc
  javaManual/asciidoc/session-api.adoc
  jsManual/asciidoc/session-api.adoc
Labels: cherry-picked, 4.3

#226 Adding a section and example on how to use multiple transactions with…
  commonManual/asciidoc/session-api.adoc
  dotnetManual/asciidoc/session-api.adoc
  javaManual/asciidoc/session-api.adoc
  jsManual/asciidoc/session-api.adoc
Labels: cherry-picked, 4.4

#196 javascript: Providing documentation and examples for Temporal types
  jsManual/asciidoc/cypher-workflow.adoc
Labels: 4.2, cherry-pick this forward, JAVASCRIPT
