Repository neo4j/docs-drivers, pull requests merged in 2021-08, with the labels that each got.

#215 Remove driver version numbers from the path to the examples
  dotnetManual/antora/antora.yml
  goManual/antora/antora.yml
  javaManual/antora/antora.yml
  jsManual/antora/antora.yml
  pythonManual/antora/antora.yml
Labels: 4.2, cherry-pick this forward

#219 Remove driver version numbers from the path to the examples
  antora/antora.yml
Labels: 1.7, THIS VERSION ONLY

#218 Remove driver version numbers from the path to the examples
  antora/antora.yml
Labels: 4.0, THIS VERSION ONLY

#217 Remove driver version numbers from the path to the examples
  antora/antora.yml
Labels: 4.1, THIS VERSION ONLY

#216 Remove driver version numbers from the path to the examples
  dotnetManual/antora/antora.yml
  goManual/antora/antora.yml
  javaManual/antora/antora.yml
  jsManual/antora/antora.yml
  pythonManual/antora/antora.yml
Labels: 4.3, THIS VERSION ONLY

#220 Added attribute for driver-version
  commonManual/asciidoc/get-started.adoc
  dotnetManual/asciidoc/get-started.adoc
  javaManual/asciidoc/get-started.adoc
  jsManual/asciidoc/get-started.adoc
  pythonManual/asciidoc/get-started.adoc
Labels: 4.3, cherry-pick this backward

#222 driver version updated for old common manual
  asciidoc/get-started.adoc
Labels: 4.1, cherry-pick this backward

#223 driver version updated for common manual (#222)
  asciidoc/get-started.adoc
Labels: cherry-picked, 4.0

#224 driver version updated for common manual (#222)
  asciidoc/get-started.adoc
Labels: cherry-picked, 1.7
