Repository neo4j/docs-drivers, pull requests merged in 2021-12, with the labels that each got.

#241 Adding examples for Javascript's geospatial types
  jsManual/asciidoc/cypher-workflow.adoc
Labels: 4.4

#242 Add examples for spatial types in Go
  goManual/asciidoc/cypher-workflow.adoc
Labels: 4.4

#197 Adding a common section on configuration options that can be provide…
  commonManual/asciidoc/session-api.adoc
  dotnetManual/antora/content-nav.adoc
  dotnetManual/asciidoc/session-api.adoc
  goManual/asciidoc/session-api.adoc
  javaManual/antora/content-nav.adoc
  javaManual/asciidoc/session-api.adoc
  jsManual/antora/content-nav.adoc
  jsManual/asciidoc/session-api.adoc
  pythonManual/antora/content-nav.adoc
  pythonManual/asciidoc/session-api.adoc
Labels: 4.2, cherry-pick this forward, GO, PYTHON, JAVASCRIPT, JAVA, .NET

#244 remove prerelease attribute from component descriptors
  dotnetManual/antora/antora.yml
  goManual/antora/antora.yml
  javaManual/antora/antora.yml
  jsManual/antora/antora.yml
  pythonManual/antora/antora.yml
Labels: THIS VERSION ONLY, 4.4

#245 Obfuscate the URL in the links to the API docs
  dotnetManual/asciidoc/get-started.adoc
  goManual/asciidoc/get-started.adoc
  javaManual/asciidoc/get-started.adoc
  jsManual/asciidoc/get-started.adoc
  pythonManual/asciidoc/get-started.adoc
Labels: 4.4, ALL DRIVERS

#246 fix a link to the Operations Manual
  commonManual/asciidoc/cypher-workflow.adoc
Labels: cherry-pick this forward, 4.4

#247 fix a link to the Operations Manual (#246)
  commonManual/asciidoc/cypher-workflow.adoc
Labels: cherry-picked

#248 Obfuscate the URL in the links to the API docs
  dotnetManual/asciidoc/get-started.adoc
  goManual/asciidoc/get-started.adoc
  javaManual/asciidoc/get-started.adoc
  jsManual/asciidoc/get-started.adoc
  pythonManual/asciidoc/get-started.adoc
Labels: cherry-picked, 4.3, ALL DRIVERS

#249 Obfuscate the URL in the links to the API docs
  dotnetManual/asciidoc/get-started.adoc
  goManual/asciidoc/get-started.adoc
  javaManual/asciidoc/get-started.adoc
  jsManual/asciidoc/get-started.adoc
  pythonManual/asciidoc/get-started.adoc
Labels: cherry-picked, 4.2, ALL DRIVERS

#243 Adding a common section on configuration options that can be provide……
  commonManual/asciidoc/session-api.adoc
  dotnetManual/antora/content-nav.adoc
  dotnetManual/asciidoc/session-api.adoc
  goManual/asciidoc/session-api.adoc
  javaManual/antora/content-nav.adoc
  javaManual/asciidoc/session-api.adoc
  jsManual/antora/content-nav.adoc
  jsManual/asciidoc/session-api.adoc
  pythonManual/antora/content-nav.adoc
  pythonManual/asciidoc/session-api.adoc
Labels: cherry-picked, 4.3, DON'T MERGE

#250 Adding a common section on configuration options
  commonManual/asciidoc/session-api.adoc
  dotnetManual/antora/content-nav.adoc
  dotnetManual/asciidoc/session-api.adoc
  goManual/asciidoc/session-api.adoc
  javaManual/antora/content-nav.adoc
  javaManual/asciidoc/session-api.adoc
  jsManual/antora/content-nav.adoc
  jsManual/asciidoc/session-api.adoc
  pythonManual/antora/content-nav.adoc
  pythonManual/asciidoc/session-api.adoc
Labels: cherry-picked, 4.4, ALL DRIVERS

#251 Adding a common section on configuration options
  commonManual/asciidoc/session-api.adoc
  dotnetManual/antora/content-nav.adoc
  dotnetManual/asciidoc/session-api.adoc
  goManual/asciidoc/session-api.adoc
  javaManual/antora/content-nav.adoc
  javaManual/asciidoc/session-api.adoc
  jsManual/antora/content-nav.adoc
  jsManual/asciidoc/session-api.adoc
  pythonManual/antora/content-nav.adoc
  pythonManual/asciidoc/session-api.adoc
Labels: cherry-picked, ALL DRIVERS, 5.0

#200 java-driver: add a section discussing the Value interface
  javaManual/asciidoc/cypher-workflow.adoc
Labels: 4.2, JAVA

#252 java-driver: add a section discussing the Value interface
  javaManual/asciidoc/cypher-workflow.adoc
Labels: cherry-picked, 4.3

#253 java-driver: add a section discussing the Value interface
  javaManual/asciidoc/cypher-workflow.adoc
Labels: cherry-picked, 4.4

#254 java-driver: add a section discussing the Value interface
  javaManual/asciidoc/cypher-workflow.adoc
Labels: cherry-picked, 5.0

#239 Add Bearer auth token section
  commonManual/asciidoc/client-applications.adoc
  dotnetManual/asciidoc/client-applications.adoc
  goManual/asciidoc/client-applications.adoc
  javaManual/asciidoc/client-applications.adoc
  jsManual/asciidoc/client-applications.adoc
  pythonManual/asciidoc/client-applications.adoc
Labels: cherry-pick this forward, 4.4
