Repository neo4j/docs-drivers, pull requests merged in 2022-11, with the labels that each got.

#339 5.0-fix-links-and-edit-url
  dotnet-manual/modules/ROOT/pages/get-started.adoc
  java-manual/modules/ROOT/pages/get-started.adoc
  javascript-manual/modules/ROOT/pages/get-started.adoc
  preview.yml
  publish.yml
  python-manual/modules/ROOT/pages/get-started.adoc
Labels: cherry-pick this forward, 5.0

#340 4.4 attributes
  dotnet-manual/modules/ROOT/pages/get-started.adoc
  java-manual/modules/ROOT/pages/get-started.adoc
  javascript-manual/modules/ROOT/pages/get-started.adoc
  preview.yml
  publish.yml
  python-manual/modules/ROOT/pages/get-started.adoc
Labels: 4.4

#341 Fix attributes (#340)
  dotnet-manual/modules/ROOT/pages/get-started.adoc
  java-manual/modules/ROOT/pages/get-started.adoc
  javascript-manual/modules/ROOT/pages/get-started.adoc
  preview.yml
  python-manual/modules/ROOT/pages/get-started.adoc
Labels: cherry-picked, 4.3

#342 Fix attributes (#340)
  dotnet-manual/modules/ROOT/pages/get-started.adoc
  java-manual/modules/ROOT/pages/get-started.adoc
  javascript-manual/modules/ROOT/pages/get-started.adoc
  preview.yml
  python-manual/modules/ROOT/pages/get-started.adoc
Labels: cherry-picked, 4.2

#343 Changing link to docs base uri
  common-content/modules/ROOT/partials/client-applications.adoc
Labels: 4.4, cherry-pick-this-to-4.3, cherry-pick-this-to-4.2

#344 4.3 cherry-pick of 343
  common-content/modules/ROOT/partials/client-applications.adoc
Labels: cherry-picked, 4.3

#346 Remove the CTA for NODES
  publish.yml
Labels: cherry-pick this backward

#354 Use new format for link
  modules/ROOT/pages/get-started.adoc
Labels: cherry-pick this backward
