Repository neo4j/docs-drivers, pull requests merged in 2022-09, with the labels that each got.

#302 Fixing inconsistency of title casing on headers
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/modules/ROOT/pages/session-api.adoc
  java-manual/modules/ROOT/content-nav.adoc
  java-manual/modules/ROOT/pages/session-api.adoc
  javascript-manual/modules/ROOT/content-nav.adoc
  javascript-manual/modules/ROOT/pages/session-api.adoc
  python-manual/modules/ROOT/content-nav.adoc
Labels: cherry-pick this forward, cherry-pick this backward, 4.4

#307 Cherry-pick of #302
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/modules/ROOT/pages/session-api.adoc
  java-manual/modules/ROOT/pages/session-api.adoc
  javascript-manual/modules/ROOT/pages/session-api.adoc
Labels: cherry-picked, 4.3

#308 cherry-pick of #302
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/modules/ROOT/pages/session-api.adoc
  java-manual/modules/ROOT/pages/session-api.adoc
  javascript-manual/modules/ROOT/pages/session-api.adoc
Labels: cherry-picked, 4.2

#309 4.1 cherry-pick of #302
  modules/ROOT/pages/session-api/asynchronous.adoc
  modules/ROOT/pages/session-api/configuration.adoc
  modules/ROOT/pages/session-api/index.adoc
  modules/ROOT/pages/session-api/reactive.adoc
  modules/ROOT/pages/session-api/simple.adoc
Labels: cherry-picked, 4.1

#310 4.0 Cherry-pick of #302
  modules/ROOT/pages/session-api.adoc
Labels: cherry-picked, 4.0

#311 5.0 cherry-pick of #302
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/modules/ROOT/pages/session-api.adoc
  java-manual/modules/ROOT/content-nav.adoc
  java-manual/modules/ROOT/pages/session-api.adoc
  javascript-manual/modules/ROOT/content-nav.adoc
  javascript-manual/modules/ROOT/pages/session-api.adoc
  python-manual/modules/ROOT/content-nav.adoc
Labels: cherry-picked, 5.0

#303 Removing extra + from ascii that was leaking on the page
  common-content/modules/ROOT/partials/session-api.adoc
Labels: BUG, cherry-pick this forward, cherry-pick this backward, 4.4

#312 5.0 cherry-pick of #303
  common-content/modules/ROOT/partials/session-api.adoc
Labels: cherry-picked, 5.0

#313 4.3 cherry-pick of #303
  common-content/modules/ROOT/partials/session-api.adoc
Labels: cherry-picked, 4.3

#314 4.2 cherry-pick of #303
  common-content/modules/ROOT/partials/session-api.adoc
Labels: cherry-picked, 4.2

#315 4.1 cherry pick of #303
  modules/ROOT/pages/session-api/asynchronous.adoc
Labels: cherry-picked, 4.1

#316 4.0 cherry-pick of #303
  modules/ROOT/pages/session-api.adoc
Labels: cherry-picked, 4.0

#305 replace tick with pdf-friendly check-mark
  common-content/modules/ROOT/partials/cypher-workflow.adoc
  preview.yml
  publish.yml
Labels: cherry-pick this forward, cherry-pick this backward, 4.4

#317 Make Implicit transactions searchable
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/modules/ROOT/pages/session-api.adoc
  java-manual/modules/ROOT/pages/session-api.adoc
  javascript-manual/modules/ROOT/pages/session-api.adoc
  python-manual/modules/ROOT/pages/session-api.adoc
Labels: cherry-pick this forward, ALL DRIVERS, 5.0

#321 Make Implicit transactions searchable (#317)
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/modules/ROOT/pages/session-api.adoc
  java-manual/modules/ROOT/pages/session-api.adoc
  javascript-manual/modules/ROOT/pages/session-api.adoc
  python-manual/modules/ROOT/pages/session-api.adoc
Labels: cherry-picked, dev branch

#319 replace tick with pdf-friendly check-mark (#305)
  common-content/modules/ROOT/partials/cypher-workflow.adoc
  preview.yml
  publish.yml
Labels: cherry-picked, 5.0

#320 replace tick with pdf-friendly check-mark (#305)
  common-content/modules/ROOT/partials/cypher-workflow.adoc
  preview.yml
Labels: cherry-picked, 4.3

#322 replace tick with pdf-friendly check-mark (#305) (#319)
  common-content/modules/ROOT/partials/cypher-workflow.adoc
  preview.yml
  publish.yml
Labels: cherry-picked, dev branch

#323 Fix broken link
  common-content/modules/ROOT/partials/cypher-workflow.adoc
Labels: 4.3

#324 Fix broken links
  common-content/modules/ROOT/partials/client-applications.adoc
  common-content/modules/ROOT/partials/session-api.adoc
Labels: 5.0, dev branch

#325 Fix link to examples
  javascript-manual/modules/ROOT/pages/client-applications.adoc
Labels: 4.2
