Repository neo4j/docs-drivers, pull requests merged in 2022-10, with the labels that each got.

#326 5.0-remote-includes (#318)
  README.adoc
  dotnet-manual/antora.yml
  fetch.js
  go-manual/antora.yml
  java-manual/antora.yml
  javascript-manual/antora.yml
  package-lock.json
  package.json
  python-manual/antora.yml
Labels: cherry-picked, 5.0

#329 Use remote includes
  README.adoc
  antora.yml
  fetch.js
  package.json
Labels: cherry-picked, 4.1

#327 4.3 remote includes (#318)
  README.adoc
  dotnet-manual/antora.yml
  fetch.js
  go-manual/antora.yml
  java-manual/antora.yml
  javascript-manual/antora.yml
  package-lock.json
  package.json
  python-manual/antora.yml
Labels: cherry-picked, 4.3

#328 4.2 remote includes (#318)
  README.adoc
  dotnet-manual/antora.yml
  fetch.js
  go-manual/antora.yml
  java-manual/antora.yml
  javascript-manual/antora.yml
  package-lock.json
  package.json
  python-manual/antora.yml
Labels: cherry-picked, 4.2

#330 Use remote includes (#329)
  README.adoc
  antora.yml
  fetch.js
  package.json
Labels: cherry-picked, 4.0

#331 Use remote includes (#329)
  README.adoc
  antora.yml
  fetch.js
  package.json
Labels: cherry-picked, 1.7

#332 Version changes for 5.0 to 5
  README.adoc
  common-content/modules/ROOT/partials/client-applications.adoc
  common-content/modules/ROOT/partials/cypher-workflow.adoc
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/antora.yml
  dotnet-manual/modules/ROOT/pages/get-started.adoc
  go-manual/antora.yml
  java-manual/antora.yml
  java-manual/modules/ROOT/pages/cypher-workflow.adoc
  java-manual/modules/ROOT/pages/get-started.adoc
  javascript-manual/antora.yml
  javascript-manual/modules/ROOT/pages/get-started.adoc
  preview.yml
  publish.yml
  python-manual/antora.yml
  python-manual/modules/ROOT/pages/client-applications.adoc
  python-manual/modules/ROOT/pages/get-started.adoc
Labels: 5.0

#333 Fix attribute path to examples
  javascript-manual/antora.yml
Labels: 4.2, cherry-pick-this-to-4.3

#336 5.0-to-5-take-2
  common-content/antora.yml
  common-content/modules/ROOT/partials/client-applications.adoc
  common-content/modules/ROOT/partials/cypher-workflow.adoc
  common-content/modules/ROOT/partials/get-started.adoc
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/antora.yml
  go-manual/antora.yml
  go-manual/modules/ROOT/pages/cypher-workflow.adoc
  java-manual/antora.yml
  javascript-manual/antora.yml
  preview.yml
  publish.yml
  python-manual/antora.yml
Labels: 5.0

#335 Update manuals according to Drivers 5.0 changes
  common-content/modules/ROOT/partials/client-applications.adoc
  common-content/modules/ROOT/partials/session-api.adoc
  dotnet-manual/modules/ROOT/pages/client-applications.adoc
  dotnet-manual/modules/ROOT/pages/cypher-workflow.adoc
  dotnet-manual/modules/ROOT/pages/session-api.adoc
  go-manual/modules/ROOT/pages/client-applications.adoc
  go-manual/modules/ROOT/pages/cypher-workflow.adoc
  go-manual/modules/ROOT/pages/session-api.adoc
  java-manual/modules/ROOT/pages/client-applications.adoc
  java-manual/modules/ROOT/pages/session-api.adoc
  javascript-manual/modules/ROOT/pages/client-applications.adoc
  javascript-manual/modules/ROOT/pages/cypher-workflow.adoc
  javascript-manual/modules/ROOT/pages/session-api.adoc
  python-manual/modules/ROOT/pages/client-applications.adoc
  python-manual/modules/ROOT/pages/cypher-workflow.adoc
  python-manual/modules/ROOT/pages/session-api.adoc
Labels: cherry-pick-this-to-5.0
