Repository neo4j/docs-drivers, pull requests merged in 2022-05, with the labels that each got.

#268 Update Go version support policy
  commonManual/asciidoc/get-started.adoc
Labels: 5.0

#270 Python 4.4 driver requires Python >= 3.6
  commonManual/asciidoc/get-started.adoc
Labels: cherry-pick this forward, 4.4

#272 Python 4.4 driver requires Python >= 3.6
  commonManual/asciidoc/get-started.adoc
Labels: cherry-picked, 4.4
